# set version of docker compose syntax
version: '3.8'

services: 
  react:
    build: .
    container_name: react
    command: npm start 0.0.0.0:3000 # Run the server!!!
    volumes:
      - .:/client # This maps any changes in the local code directly to the docker container!
    ports:
      -  "3000:3000" # Maps container's 3000 port to our machine's 3000 port