# set version of docker compose syntax
version: '3.8'

services: 
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000 # Run the server!!!
    volumes:
      - .:/server # This maps any changes in the local code directly to the docker container!
    ports:
      -  "8000:8000" # Maps container's 8000 port to our machine's 8000 port