# Generated by Django 4.1.2 on 2022-11-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='end_time',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='start_time',
            field=models.CharField(max_length=7),
        ),
    ]
